language: rust

env:
  global:
    - secure: IV/0GyGaGQKlKgf7zLB5URYHjLJadKYACbjZ0Z+/uPWAmJ/d9MYq990yUziQrkVIE5+0/eeaJ8eR6r65CNuFmS09w1/Y4jKpVkZ9zqWH2YXKn/FlccSIzXZqnIROqST/3DQ3Sm/A/777kp9OcagVTAq9m3qXX3tr1sXvR4r+4uM=

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install libgdal-dev libgdal1-dev libproj-dev libgdal1h

script:
  - cargo test
  - cargo doc

after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
