[package]
name = "gdal"
description = "GDAL bindings for Rust"
license = "MIT"
version = "0.3.1"
authors = ["Alex Morega <alex@grep.ro>"]
repository = "https://github.com/georust/rust-gdal"
documentation = "https://georust.github.io/rust-gdal/"

[features]
bindgen = ["gdal-sys/bindgen"]
min_gdal_version_1_11 = ["gdal-sys/min_gdal_version_1_11"]
min_gdal_version_2_0 = ["gdal-sys/min_gdal_version_2_0"]
min_gdal_version_2_1 = ["gdal-sys/min_gdal_version_2_1"]
min_gdal_version_2_2 = ["gdal-sys/min_gdal_version_2_2"]

[dependencies]
error-chain = "0.11"
libc = "0.2"
geo = "0.7"
gdal-sys = { path = "gdal-sys", version = "0.1"}
num-traits = "0.2"

[workspace]
members = ["gdal-sys"]
