[package]
name = "gdal"
description = "GDAL bindings for Rust"
license = "MIT"
version = "0.4.0"
authors = [
    "Alex Morega <alex@grep.ro>",
    "Johannes Drönner <droenner@informatik.uni-marburg.de>"
    ]
repository = "https://github.com/georust/rust-gdal"
documentation = "https://georust.github.io/rust-gdal/"

[features]
bindgen = ["gdal-sys/bindgen"]

[dependencies]
failure = "0.1"
failure_derive = "0.1"
libc = "0.2"
geo-types = "0.1"
# gdal-sys = { path = "gdal-sys", version = "0.2"}
gdal-sys = "0.2"
num-traits = "0.2"

[workspace]
members = ["gdal-sys"]
