[package]
name = "gdal"
description = "GDAL bindings for Rust"
license = "MIT"
version = "0.1.0"
authors = ["Alex Morega <alex@grep.ro>"]
repository = "https://github.com/georust/rust-gdal"
documentation = "http://georust.github.io/rust-gdal/"

[dependencies]
libc = "0.1.7"
