[package]
name = "gdal"
description = "GDAL bindings for Rust"
license = "MIT"
version = "0.1.1"
authors = ["Alex Morega <alex@grep.ro>"]
repository = "https://github.com/georust/rust-gdal"
documentation = "http://georust.github.io/rust-gdal/"

[dependencies]
libc = "0.1.7"

[dependencies.geo]
git = "https://github.com/georust/rust-geo.git"
rev = "b3f2f81"
