[package]
name = "gdal"
description = "GDAL bindings for Rust"
license = "MIT"
version = "0.2.1"
authors = ["Alex Morega <alex@grep.ro>"]
repository = "https://github.com/georust/rust-gdal"
documentation = "https://georust.github.io/rust-gdal/"

[dependencies]
error-chain = "0.7.2"
libc = "0.2.20"
geo = "0.0.5"
gdal-sys = { path = "gdal-sys", version = "0.1.0"}

[workspace]
members = ["gdal-sys"]
