[package]
name = "gdal-sys"
description = "Low level GDAL bindings for Rust"
license = "MIT"
version = "0.1.1"
repository = "https://github.com/georust/rust-gdal"
authors = ["Johannes Drönner <droenner@informatik.uni-marburg.de>"]

[features]
default = ["min_gdal_version_1_11"]
min_gdal_version_1_11 = []
min_gdal_version_2_0 = []
min_gdal_version_2_1 = []
min_gdal_version_2_2 = []

[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = { version = "0.33.0", optional = true }
pkg-config = "0.3"
